### ISSUE TITLE
npsql versions

### ISSUE THREAD

**Issue by mickdelaney** [danbarua/SqlStreamStore#3]
Hi,

I'm trying to get up and running with cedar.eventstore on postgres, so naturally i came across your fork.
I've hit a few errors and was wondering if you'd seen them before. 

I've not been able to find Npgsql "3.1.0-unstable0000"

I've tried "3.1.0-alpha3" but it fails by not recognizing: 

{"42883: function public.read_stream_forward(stream_id := text, count := integer, stream_version := integer) does not exist"}

Then I went back to the latest stable, but it fails on line: 
var isDeleted = reader.GetBoolean(1);

The result set returned is "<unnamed portal 1>, 2 & 3".   

Apparently its because the Npgsql driver is not dereferencing the stored procedure cursors. 

Anyways, i was wondering if these issues also happened to you ??

**Comment by mickdelaney** [comment]
i managed to get it to load the ref cursors by modifying the C# code. 

in ReadStream:

using (var command = new NpgsqlCommand(commandText, connection, tx) { 
CommandType = CommandType.StoredProcedure }) {
command.Parameters.AddWithValue(":stream_id", NpgsqlDbType.Text, streamIdInfo.StreamId);
command.Parameters.AddWithValue(":count", NpgsqlDbType.Integer, count + 1); 
command.Parameters.AddWithValue(":stream_version", NpgsqlDbType.Integer, StreamVersion);

await command.ExecuteNonQueryAsync(cancellationToken);

command.CommandText = "
fetch all in <unnamed portal 1>\; 
fetch all in <unnamed portal 2>\; 
fetch all in <unnamed portal 3>\; 
";
command.CommandType = CommandType.Text;

List<StreamEvent> streamEvents = new List<StreamEvent>();

**Comment by danbarua** [comment]
Hi, good to have someone else kicking the tires.
You need to add the [npgsql unstable package source](https://www.myget.org/F/npgsql-unstable) to your NuGet sources. We might be ok to move to the stable release now it's out, I will take a look at it tomorrow.

**Comment by danbarua** [comment]
Seems to be working ok with Npgsql `3.0.3`
Note tests that are currently failing - Damien wants Cedar implementations to be compatible with `GetEventStore`, that is, re-inserting events that already exist should not throw exceptions, and also behaviour when reading to the end of the `All` stream.

**Comment by mickdelaney** [comment]
I'm getting 9 failed out of the 29 in PostgresEventStoreTests.cs
is that what your seeing ??

so what is the plan around the broken tests ?? are you going to wait until damian has sorted out his SQL server implementation ? 

i'd prefer to stay api compatible with GES also but is it feasible ??
what work do we need to do to fix all the tests, (happy to help out etc)

**Comment by danbarua** [comment]
GES has some funny properties - when you are reading from "all streams", this includes the GES system event streams as well as your own, so you may have read past the end of your events but you won't reach the end of the events handed back to you by GES (Cedar discards 'system' events under the hood, as far as I can see.)

The other issue is idempotency - if I commit a sequence of events, if the contents of the events match those events in the sequence for that stream then it should just ignore and not throw any errors. As far as I can remember I just haven't bothered to implement it yet because it's not behaviour I need.

**Comment by danbarua** [comment]
![image](https://cloud.githubusercontent.com/assets/469192/11040967/e9e45602-8706-11e5-8dbb-44d7172f0e1a.png)
These are the tests in question re: GES-like behaviour - they're duplicated in SecondarySchemaTests.

**Comment by mickdelaney** [comment]
Ok thanks. 
I'm happy to ignore the idempotency for now, i'm interested in staying close to GES but we're not planning to switch to it immediately. The priority is to get a solid postgres ES in place.

**Comment by danbarua** [comment]
@mickdelaney This has now been merged into https://github.com/damianh/Cedar.EventStore but feel free to open up an Postgres discussions or issues here.

**Comment by mickdelaney** [comment]
cheers dan..
